"""add_github_installation_id_to_users

Revision ID: ccf0a808e05e
Revises: 
Create Date: 2026-04-22 17:53:24.282121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ccf0a808e05e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_installation_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_installation_id')
    # ### end Alembic commands ###
