export { OnboardingDecorativePanel } from './onboarding-decorative-panel'
export { OnboardingStepIndicator } from './onboarding-step-indicator'
export { StepProjectName } from './step-project-name'
export { StepGithubConnect } from './step-github-connect'
export { StepSelectAgents } from './step-select-agents'
export { StepFinish } from './step-finish'
export type { MockAgent } from './mock-agents'
export { MOCK_AGENTS } from './mock-agents'
